fix: Invoice
solop-develop/vue-1.0 pull request #2199
Opened 2024-05-03 12:49 UTC by Ricargame

## Bug report / Feature
Search > Sales/Purchase Invoice
#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Screenshot or Gif

https://github.com/solop-develop/frontend-core/assets/78000356/3ee0364c-2c46-45e7-b479-c4dbc682c4df

#### Link to minimal reproduction

#### Expected behavior
A clear and concise description of what you expected to happen.

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- Yarn version:
- adempiere-vue version: 

#### Additional context
Add any other context about the problem here.

fixed: https://github.com/solop-develop/frontend-core/issues/468

2024-05-03 15:43 UTC, Ricargame commented
![image](https://github.com/solop-develop/frontend-core/assets/78000356/4d444323-3a5b-48fc-b261-1d1cec5287a0)

2024-05-05 21:51 UTC, EdwinBetanc0urt requested changes

2024-05-05 21:51 UTC, EdwinBetanc0urt commented on src/components/ADempiere/FieldDefinition/FieldSearch/GeneralInfoSearch/panel.vue
> +        <query-criteria
Discard all changes on this file. The changes in this file have nothing to do with the scope of the pull reques

2024-05-06 17:53 UTC, Ricargame commented
https://github.com/solop-develop/frontend-core/assets/78000356/65140e5a-d0ee-43d3-8b34-828752b4addf

2024-05-06 19:33 UTC, merged