Create a Dynamic MarkDown Component
solop-develop/vue-1.0 pull request #2556
Opened 2024-08-02 14:16 UTC by elsiosanchez

#### Screenshot or Gif
=

https://github.com/user-attachments/assets/622a850d-3333-4541-9826-51cd6ad4216b

2024-08-02 14:27 UTC, EdwinBetanc0urt requested changes
I don't think it should have the buttons inside the component, instead it should handle properties to get the value and to set the value, but not the buttons that are proper for the components that contain it like modals, drawer or others.

2024-08-03 01:53 UTC, EdwinBetanc0urt approved these changes

2024-08-03 03:03 UTC, elsiosanchez commented
> No creo que deba tener los botones dentro del componente, en lugar de eso debería manejar propiedades para obtener el valor y establecer el valor, pero no los botones que son apropiados para los componentes que lo contienen como modales, cajón u otros.

https://github.com/solop-develop/frontend-core/pull/2556/commits/17ea22104570c8cc16f5912798c1e8f25903642b

2024-08-03 14:36 UTC, EdwinBetanc0urt approved these changes

2024-08-03 14:36 UTC, merged