Validate POS
solop-develop/vue-1.0 pull request #2828
Opened 2024-10-17 19:47 UTC by elsiosanchez

#### Screenshot or Gif

https://github.com/user-attachments/assets/5f3a775b-45ad-4faa-8358-983c52383ca9

2024-10-17 21:51 UTC, yamelsenih requested changes
This is unnecessary

2024-10-17 21:51 UTC, yamelsenih commented on src/store/modules/ADempiere/form/VPOS/index.js
> -        if (isEmptyValue(posId)) {
This is unnecessary

2024-10-18 14:24 UTC, elsiosanchez commented on src/store/modules/ADempiere/form/VPOS/index.js
> -        if (isEmptyValue(posId)) {
Yes, that's why I deleted it.

2024-10-18 14:57 UTC, EdwinBetanc0urt approved these changes

2024-10-18 14:57 UTC, merged